/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kaede256 (https://sketchfab.com/kaede256)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-earth-bce3ea48781c4f02a8c52d2678220d07
Title: Planet Earth
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Earth_Ice_0: THREE.Mesh;
    Earth_Water_0: THREE.Mesh;
    Earth_Sand_0: THREE.Mesh;
    Earth_Grass_0: THREE.Mesh;
    Earth_Details_Wood_0: THREE.Mesh;
    Earth_Details_Tree_0: THREE.Mesh;
    Earth_Details_Tree_0_1: THREE.Mesh;
    Earth_Details_Ice_0: THREE.Mesh;
    Earth_Details_Blue_0: THREE.Mesh;
    Earth_Details_Sand_0: THREE.Mesh;
    Earth_Details_red_0: THREE.Mesh;
    Clouds_and_Stars_Ice_0: THREE.Mesh;
    Clouds_and_Stars_Star_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    Water: THREE.MeshStandardMaterial;
    Sand: THREE.MeshStandardMaterial;
    Grass: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    Tree: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    material_7: THREE.MeshStandardMaterial;
    Star: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Earth Turn";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function Planet(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "./models/planet_earth.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<GLTFActions>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group
            name="578a67fb859c4432ad395a9d408af1e7fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Earth"
                  rotation={[-Math.PI / 2, 0, 0.681]}
                  scale={358.622}
                >
                  <mesh
                    name="Earth_Ice_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Earth_Ice_0.geometry}
                    material={materials.material}
                  />
                  <mesh
                    name="Earth_Water_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Earth_Water_0.geometry}
                    material={materials.Water}
                  />
                  <mesh
                    name="Earth_Sand_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Earth_Sand_0.geometry}
                    material={materials.Sand}
                  />
                  <mesh
                    name="Earth_Grass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Earth_Grass_0.geometry}
                    material={materials.Grass}
                  />
                  <group
                    name="Earth_Details"
                    position={[0.163, -0.812, 0.592]}
                    rotation={[-0.525, -0.789, -2.962]}
                    scale={[0.006, 0.006, 0.009]}
                  >
                    <mesh
                      name="Earth_Details_Wood_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Wood_0.geometry}
                      material={materials.Wood}
                    />
                    <mesh
                      name="Earth_Details_Tree_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Tree_0.geometry}
                      material={materials.Tree}
                    />
                    <mesh
                      name="Earth_Details_Tree_0_1"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Tree_0_1.geometry}
                      material={materials.Tree}
                    />
                    <mesh
                      name="Earth_Details_Ice_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Ice_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="Earth_Details_Blue_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Blue_0.geometry}
                      material={materials.Blue}
                    />
                    <mesh
                      name="Earth_Details_Sand_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_Sand_0.geometry}
                      material={materials.Sand}
                    />
                    <mesh
                      name="Earth_Details_red_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Earth_Details_red_0.geometry}
                      material={materials.material_7}
                    />
                  </group>
                  <group
                    name="Clouds_and_Stars"
                    position={[-0.577, -0.085, 0.844]}
                    rotation={[-1.555, -0.135, 2.627]}
                    scale={0.042}
                  >
                    <mesh
                      name="Clouds_and_Stars_Ice_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Clouds_and_Stars_Ice_0.geometry}
                      material={materials.material}
                    />
                    <mesh
                      name="Clouds_and_Stars_Star_0"
                      castShadow
                      receiveShadow
                      geometry={nodes.Clouds_and_Stars_Star_0.geometry}
                      material={materials.Star}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/planet_earth.glb");
